/* SPDX-License-Identifier: MIT */
#ifndef RINDX_SRC_DXGI_NATIVE_ADAPTER_IDS_H
#define RINDX_SRC_DXGI_NATIVE_ADAPTER_IDS_H

#define RINDX_NATIVE_SOFTWARE_ADAPTER_VENDOR_ID 0x52494e44u
#define RINDX_NATIVE_SOFTWARE_ADAPTER_DEVICE_ID 0x00000001u

#endif /* RINDX_SRC_DXGI_NATIVE_ADAPTER_IDS_H */
